In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.base import BaseEstimator

class MyDummyClassifier(BaseEstimator):
    
    def fit(self, x, y=None):
        pass
    
    def predict(self, x):
        pred = np.zeros((x.shape[0], 1))
        
        for i in range(x.shape[0]):
            if x['Sex'].iloc[i] == 1:
                pred[i] = 0
            else:
                pred[i]  = 1
                
        return pred

In [3]:
from sklearn.preprocessing import LabelEncoder

def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace=True)
    return df

def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
    return df

def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    return df

def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

titanic_df = pd.read_csv('./ml_data/titanic_data.csv')
y_titanic_df = titanic_df['Survived']

FileNotFoundError: [Errno 2] No such file or directory: './ml_data/titanic_data.csv'

In [ ]:
titanic_df.head(2)

In [5]:
x_titanic_df = titanic_df.drop('Survived', axis=1)
x_titanic_df = transform_features(x_titanic_df)
x_titanic_df

NameError: name 'titanic_df' is not defined

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x_titanic_df, y_titanic_df, test_size=0.2)

NameError: name 'x_titanic_df' is not defined

In [7]:
myclf = MyDummyClassifier()
myclf.fit(x_train, y_train)

mypredictions = myclf.predict(x_test)
accuracy_score(y_test, mypredictions)

NameError: name 'x_train' is not defined

In [41]:
mypredictions

array([[1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],

In [42]:
for i in range(len(x_test)):
    print(mypredictions[i], x_test.iloc[i])

[1.] Pclass       3.000
Sex          0.000
Age         21.000
SibSp        1.000
Parch        0.000
Fare         9.825
Cabin        7.000
Embarked     3.000
Name: 402, dtype: float64
[1.] Pclass       3.000
Sex          0.000
Age          8.000
SibSp        3.000
Parch        1.000
Fare        21.075
Cabin        7.000
Embarked     3.000
Name: 24, dtype: float64
[0.] Pclass       1.000
Sex          1.000
Age         45.000
SibSp        1.000
Parch        0.000
Fare        83.475
Cabin        2.000
Embarked     3.000
Name: 62, dtype: float64
[0.] Pclass        1.000000
Sex           1.000000
Age          29.699118
SibSp         0.000000
Parch         0.000000
Fare        221.779200
Cabin         2.000000
Embarked      3.000000
Name: 527, dtype: float64
[1.] Pclass       3.000000
Sex          0.000000
Age         29.699118
SibSp        0.000000
Parch        0.000000
Fare         7.750000
Cabin        7.000000
Embarked     2.000000
Name: 274, dtype: float64
[0.] Pclass       3.00
Sex     

In [50]:
from sklearn.datasets import load_digits
from sklearn.base import BaseEstimator

In [52]:
class MyFakeClassifier(BaseEstimator):
    def fit(self, x, y):
        pass
    
    def predict(self, x):
        return np.zeros((len(x),1), dtype=bool)

In [53]:
digits = load_digits()

In [55]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [56]:
digits.data.shape  # 0~9 수를 길이 64 vector가 나타내는데, 그런 데이터가 1797개 존재...

(1797, 64)

In [57]:
digits.target  

array([0, 1, 2, ..., 8, 9, 8])

In [58]:
len(digits.target)

1797

In [59]:
digits.target == 7

array([False, False, False, ..., False, False, False])

In [61]:
y = (digits.target == 7).astype(int)

In [62]:
x = digits.data

In [63]:
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=11)

In [64]:
fakeclf = MyFakeClassifier()
fakeclf.fit(x_train, y_train)
fakepred = fakeclf.predict(x_test)

In [65]:
accuracy_score(y_test, fakepred)

0.9

In [68]:
from sklearn.metrics import confusion_matrix, classification_report

In [67]:
confusion_matrix(y_test, fakepred)

array([[405,   0],
       [ 45,   0]], dtype=int64)

In [69]:
print(classification_report(y_test, fakepred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95       405
           1       0.00      0.00      0.00        45

    accuracy                           0.90       450
   macro avg       0.45      0.50      0.47       450
weighted avg       0.81      0.90      0.85       450



C:\Users\YONSAI\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\YONSAI\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\YONSAI\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# accuray, recall, precision, f1_score
# precision_recall_score, roc_auc_score